### ISSUE TITLE
Workaround to install SDK on Mint (Ubuntu based) but without gdb.

### ISSUE THREAD

**Issue by joseluisquiroga** [adapteva/epiphany-sdk#70]
To install the SDK in Mint:

1. Install all packages in https://github.com/adapteva/epiphany-sdk/wiki/Building-on-Linux
and **also**:

2. sudo apt-get install guile-1.8 dh-autoreconf

(it did not build with guile-2.0)

3. Do not build nor install gdb because it fails with "Build Error, multiple definitions of 'xmalloc'":

Edit the file ./sdk/build-toolchain.sh
find the string "Building tool chain..."
remove parameter "all-gdb" passed to make

find the string "Installing tool chain..."
remove parameter "install-gdb" passed to make

4. run ./sdk/build-epiphany-sdk.sh

======================================================================
PS:

I have this Linux

jose@my-desktop ~ $ uname -a
Linux my-desktop 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
jose@my-desktop ~ $ cat /etc/lsb-release 
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18
DISTRIB_CODENAME=sarah
DISTRIB_DESCRIPTION="Linux Mint 18 Sarah"

**Comment by codeSober** [comment]
thank you Jose!! removing those lines in build-toolchain allowed me to build successfully!!

i wonder what the 'gdb' build in the toolchain does

**Comment by joseluisquiroga** [comment]
It is the gnu debugger. But some thing tells me you already knew that.

Thank you for encouraging me to contribute. 

I wonder what your contributing user is.






Enviado desde Samsung tablet

-------- Original message --------
From codeSober <notifications@github.com> 
Date: 17/12/2016  9:14 AM  (GMT-05:00) 
To adapteva/epiphany-sdk <epiphany-sdk@noreply.github.com> 
Cc Jose Luis Quiroga Beltran <joseluisquirogabeltran@gmail.com>,Author <author@noreply.github.com> 
Subject Re: [adapteva/epiphany-sdk] Workaround to install SDK on Mint (Ubuntu
  based) but without gdb. (#70) 
 
thank you Jose!! removing those lines in build-toolchain allowed me to build successfully!!

i wonder what the 'gdb' build in the toolchain does
